// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_client.proto

#include "msg_client.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace PB {
class MsgSvrDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MsgSvr>
      _instance;
} _MsgSvr_default_instance_;
class MsgSvrListDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MsgSvrList>
      _instance;
} _MsgSvrList_default_instance_;
class MsgExecCommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MsgExecCommand>
      _instance;
} _MsgExecCommand_default_instance_;
}  // namespace PB
namespace protobuf_msg_5fclient_2eproto {
void InitDefaultsMsgSvrImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::PB::_MsgSvr_default_instance_;
    new (ptr) ::PB::MsgSvr();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PB::MsgSvr::InitAsDefaultInstance();
}

void InitDefaultsMsgSvr() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMsgSvrImpl);
}

void InitDefaultsMsgSvrListImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_msg_5fclient_2eproto::InitDefaultsMsgSvr();
  {
    void* ptr = &::PB::_MsgSvrList_default_instance_;
    new (ptr) ::PB::MsgSvrList();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PB::MsgSvrList::InitAsDefaultInstance();
}

void InitDefaultsMsgSvrList() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMsgSvrListImpl);
}

void InitDefaultsMsgExecCommandImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_msg_5fclient_2eproto::InitDefaultsMsgSvr();
  {
    void* ptr = &::PB::_MsgExecCommand_default_instance_;
    new (ptr) ::PB::MsgExecCommand();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PB::MsgExecCommand::InitAsDefaultInstance();
}

void InitDefaultsMsgExecCommand() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMsgExecCommandImpl);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgSvr, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgSvr, shard_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgSvr, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgSvr, sid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgSvr, ip_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgSvrList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgSvrList, svrlist_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgExecCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgExecCommand, svrlist_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgExecCommand, command_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgExecCommand, result_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgExecCommand, runms_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PB::MsgExecCommand, from_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::PB::MsgSvr)},
  { 9, -1, sizeof(::PB::MsgSvrList)},
  { 15, -1, sizeof(::PB::MsgExecCommand)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::PB::_MsgSvr_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::PB::_MsgSvrList_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::PB::_MsgExecCommand_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "msg_client.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020msg_client.proto\022\002PB\">\n\006MsgSvr\022\r\n\005shar"
      "d\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\013\n\003sid\030\003 \001(\005\022\n\n\002ip"
      "\030\004 \001(\t\")\n\nMsgSvrList\022\033\n\007svrlist\030\001 \003(\0132\n."
      "PB.MsgSvr\"k\n\016MsgExecCommand\022\033\n\007svrlist\030\001"
      " \003(\0132\n.PB.MsgSvr\022\017\n\007command\030\002 \001(\t\022\016\n\006res"
      "ult\030\003 \001(\t\022\r\n\005runms\030\004 \001(\005\022\014\n\004from\030\005 \001(\tb\006"
      "proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 246);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg_client.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_msg_5fclient_2eproto
namespace PB {

// ===================================================================

void MsgSvr::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgSvr::kShardFieldNumber;
const int MsgSvr::kNameFieldNumber;
const int MsgSvr::kSidFieldNumber;
const int MsgSvr::kIpFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgSvr::MsgSvr()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_msg_5fclient_2eproto::InitDefaultsMsgSvr();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:PB.MsgSvr)
}
MsgSvr::MsgSvr(const MsgSvr& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  shard_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.shard().size() > 0) {
    shard_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.shard_);
  }
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ip().size() > 0) {
    ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ip_);
  }
  sid_ = from.sid_;
  // @@protoc_insertion_point(copy_constructor:PB.MsgSvr)
}

void MsgSvr::SharedCtor() {
  shard_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sid_ = 0;
  _cached_size_ = 0;
}

MsgSvr::~MsgSvr() {
  // @@protoc_insertion_point(destructor:PB.MsgSvr)
  SharedDtor();
}

void MsgSvr::SharedDtor() {
  shard_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MsgSvr::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgSvr::descriptor() {
  ::protobuf_msg_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_msg_5fclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MsgSvr& MsgSvr::default_instance() {
  ::protobuf_msg_5fclient_2eproto::InitDefaultsMsgSvr();
  return *internal_default_instance();
}

MsgSvr* MsgSvr::New(::google::protobuf::Arena* arena) const {
  MsgSvr* n = new MsgSvr;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgSvr::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.MsgSvr)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  shard_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sid_ = 0;
  _internal_metadata_.Clear();
}

bool MsgSvr::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PB.MsgSvr)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string shard = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_shard()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->shard().data(), static_cast<int>(this->shard().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PB.MsgSvr.shard"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PB.MsgSvr.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 sid = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string ip = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ip().data(), static_cast<int>(this->ip().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PB.MsgSvr.ip"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PB.MsgSvr)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PB.MsgSvr)
  return false;
#undef DO_
}

void MsgSvr::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PB.MsgSvr)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string shard = 1;
  if (this->shard().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->shard().data(), static_cast<int>(this->shard().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgSvr.shard");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->shard(), output);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgSvr.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // int32 sid = 3;
  if (this->sid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->sid(), output);
  }

  // string ip = 4;
  if (this->ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ip().data(), static_cast<int>(this->ip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgSvr.ip");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->ip(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PB.MsgSvr)
}

::google::protobuf::uint8* MsgSvr::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PB.MsgSvr)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string shard = 1;
  if (this->shard().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->shard().data(), static_cast<int>(this->shard().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgSvr.shard");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->shard(), target);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgSvr.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // int32 sid = 3;
  if (this->sid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->sid(), target);
  }

  // string ip = 4;
  if (this->ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ip().data(), static_cast<int>(this->ip().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgSvr.ip");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->ip(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.MsgSvr)
  return target;
}

size_t MsgSvr::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.MsgSvr)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string shard = 1;
  if (this->shard().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->shard());
  }

  // string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string ip = 4;
  if (this->ip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ip());
  }

  // int32 sid = 3;
  if (this->sid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgSvr::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PB.MsgSvr)
  GOOGLE_DCHECK_NE(&from, this);
  const MsgSvr* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgSvr>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PB.MsgSvr)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PB.MsgSvr)
    MergeFrom(*source);
  }
}

void MsgSvr::MergeFrom(const MsgSvr& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PB.MsgSvr)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.shard().size() > 0) {

    shard_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.shard_);
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.ip().size() > 0) {

    ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ip_);
  }
  if (from.sid() != 0) {
    set_sid(from.sid());
  }
}

void MsgSvr::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PB.MsgSvr)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgSvr::CopyFrom(const MsgSvr& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.MsgSvr)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgSvr::IsInitialized() const {
  return true;
}

void MsgSvr::Swap(MsgSvr* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgSvr::InternalSwap(MsgSvr* other) {
  using std::swap;
  shard_.Swap(&other->shard_);
  name_.Swap(&other->name_);
  ip_.Swap(&other->ip_);
  swap(sid_, other->sid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgSvr::GetMetadata() const {
  protobuf_msg_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_msg_5fclient_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MsgSvrList::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgSvrList::kSvrlistFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgSvrList::MsgSvrList()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_msg_5fclient_2eproto::InitDefaultsMsgSvrList();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:PB.MsgSvrList)
}
MsgSvrList::MsgSvrList(const MsgSvrList& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      svrlist_(from.svrlist_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:PB.MsgSvrList)
}

void MsgSvrList::SharedCtor() {
  _cached_size_ = 0;
}

MsgSvrList::~MsgSvrList() {
  // @@protoc_insertion_point(destructor:PB.MsgSvrList)
  SharedDtor();
}

void MsgSvrList::SharedDtor() {
}

void MsgSvrList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgSvrList::descriptor() {
  ::protobuf_msg_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_msg_5fclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MsgSvrList& MsgSvrList::default_instance() {
  ::protobuf_msg_5fclient_2eproto::InitDefaultsMsgSvrList();
  return *internal_default_instance();
}

MsgSvrList* MsgSvrList::New(::google::protobuf::Arena* arena) const {
  MsgSvrList* n = new MsgSvrList;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgSvrList::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.MsgSvrList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  svrlist_.Clear();
  _internal_metadata_.Clear();
}

bool MsgSvrList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PB.MsgSvrList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .PB.MsgSvr svrlist = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_svrlist()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PB.MsgSvrList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PB.MsgSvrList)
  return false;
#undef DO_
}

void MsgSvrList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PB.MsgSvrList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .PB.MsgSvr svrlist = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->svrlist_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->svrlist(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PB.MsgSvrList)
}

::google::protobuf::uint8* MsgSvrList::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PB.MsgSvrList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .PB.MsgSvr svrlist = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->svrlist_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->svrlist(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.MsgSvrList)
  return target;
}

size_t MsgSvrList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.MsgSvrList)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .PB.MsgSvr svrlist = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->svrlist_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->svrlist(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgSvrList::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PB.MsgSvrList)
  GOOGLE_DCHECK_NE(&from, this);
  const MsgSvrList* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgSvrList>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PB.MsgSvrList)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PB.MsgSvrList)
    MergeFrom(*source);
  }
}

void MsgSvrList::MergeFrom(const MsgSvrList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PB.MsgSvrList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  svrlist_.MergeFrom(from.svrlist_);
}

void MsgSvrList::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PB.MsgSvrList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgSvrList::CopyFrom(const MsgSvrList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.MsgSvrList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgSvrList::IsInitialized() const {
  return true;
}

void MsgSvrList::Swap(MsgSvrList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgSvrList::InternalSwap(MsgSvrList* other) {
  using std::swap;
  svrlist_.InternalSwap(&other->svrlist_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgSvrList::GetMetadata() const {
  protobuf_msg_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_msg_5fclient_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MsgExecCommand::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgExecCommand::kSvrlistFieldNumber;
const int MsgExecCommand::kCommandFieldNumber;
const int MsgExecCommand::kResultFieldNumber;
const int MsgExecCommand::kRunmsFieldNumber;
const int MsgExecCommand::kFromFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgExecCommand::MsgExecCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_msg_5fclient_2eproto::InitDefaultsMsgExecCommand();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:PB.MsgExecCommand)
}
MsgExecCommand::MsgExecCommand(const MsgExecCommand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      svrlist_(from.svrlist_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.command().size() > 0) {
    command_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.command_);
  }
  result_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.result().size() > 0) {
    result_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.result_);
  }
  from_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.from().size() > 0) {
    from_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.from_);
  }
  runms_ = from.runms_;
  // @@protoc_insertion_point(copy_constructor:PB.MsgExecCommand)
}

void MsgExecCommand::SharedCtor() {
  command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  result_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  from_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  runms_ = 0;
  _cached_size_ = 0;
}

MsgExecCommand::~MsgExecCommand() {
  // @@protoc_insertion_point(destructor:PB.MsgExecCommand)
  SharedDtor();
}

void MsgExecCommand::SharedDtor() {
  command_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  result_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  from_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MsgExecCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgExecCommand::descriptor() {
  ::protobuf_msg_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_msg_5fclient_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MsgExecCommand& MsgExecCommand::default_instance() {
  ::protobuf_msg_5fclient_2eproto::InitDefaultsMsgExecCommand();
  return *internal_default_instance();
}

MsgExecCommand* MsgExecCommand::New(::google::protobuf::Arena* arena) const {
  MsgExecCommand* n = new MsgExecCommand;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgExecCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.MsgExecCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  svrlist_.Clear();
  command_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  result_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  from_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  runms_ = 0;
  _internal_metadata_.Clear();
}

bool MsgExecCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PB.MsgExecCommand)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .PB.MsgSvr svrlist = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_svrlist()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string command = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_command()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->command().data(), static_cast<int>(this->command().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PB.MsgExecCommand.command"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string result = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_result()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->result().data(), static_cast<int>(this->result().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PB.MsgExecCommand.result"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 runms = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &runms_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string from = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_from()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->from().data(), static_cast<int>(this->from().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PB.MsgExecCommand.from"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PB.MsgExecCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PB.MsgExecCommand)
  return false;
#undef DO_
}

void MsgExecCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PB.MsgExecCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .PB.MsgSvr svrlist = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->svrlist_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->svrlist(static_cast<int>(i)), output);
  }

  // string command = 2;
  if (this->command().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->command().data(), static_cast<int>(this->command().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgExecCommand.command");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->command(), output);
  }

  // string result = 3;
  if (this->result().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->result().data(), static_cast<int>(this->result().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgExecCommand.result");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->result(), output);
  }

  // int32 runms = 4;
  if (this->runms() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->runms(), output);
  }

  // string from = 5;
  if (this->from().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->from().data(), static_cast<int>(this->from().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgExecCommand.from");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->from(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PB.MsgExecCommand)
}

::google::protobuf::uint8* MsgExecCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PB.MsgExecCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .PB.MsgSvr svrlist = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->svrlist_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->svrlist(static_cast<int>(i)), deterministic, target);
  }

  // string command = 2;
  if (this->command().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->command().data(), static_cast<int>(this->command().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgExecCommand.command");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->command(), target);
  }

  // string result = 3;
  if (this->result().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->result().data(), static_cast<int>(this->result().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgExecCommand.result");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->result(), target);
  }

  // int32 runms = 4;
  if (this->runms() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->runms(), target);
  }

  // string from = 5;
  if (this->from().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->from().data(), static_cast<int>(this->from().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB.MsgExecCommand.from");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->from(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.MsgExecCommand)
  return target;
}

size_t MsgExecCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.MsgExecCommand)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .PB.MsgSvr svrlist = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->svrlist_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->svrlist(static_cast<int>(i)));
    }
  }

  // string command = 2;
  if (this->command().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->command());
  }

  // string result = 3;
  if (this->result().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->result());
  }

  // string from = 5;
  if (this->from().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->from());
  }

  // int32 runms = 4;
  if (this->runms() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->runms());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgExecCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PB.MsgExecCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const MsgExecCommand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgExecCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PB.MsgExecCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PB.MsgExecCommand)
    MergeFrom(*source);
  }
}

void MsgExecCommand::MergeFrom(const MsgExecCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PB.MsgExecCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  svrlist_.MergeFrom(from.svrlist_);
  if (from.command().size() > 0) {

    command_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.command_);
  }
  if (from.result().size() > 0) {

    result_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.result_);
  }
  if (from.from().size() > 0) {

    from_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.from_);
  }
  if (from.runms() != 0) {
    set_runms(from.runms());
  }
}

void MsgExecCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PB.MsgExecCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgExecCommand::CopyFrom(const MsgExecCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.MsgExecCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgExecCommand::IsInitialized() const {
  return true;
}

void MsgExecCommand::Swap(MsgExecCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgExecCommand::InternalSwap(MsgExecCommand* other) {
  using std::swap;
  svrlist_.InternalSwap(&other->svrlist_);
  command_.Swap(&other->command_);
  result_.Swap(&other->result_);
  from_.Swap(&other->from_);
  swap(runms_, other->runms_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgExecCommand::GetMetadata() const {
  protobuf_msg_5fclient_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_msg_5fclient_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace PB

// @@protoc_insertion_point(global_scope)
